[package]
name = "run-on-change"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.0.0"
globset = "0.4"
clap = { version = "4.0.29", features = ["derive"] }
